application: care-tiger
version: 1-1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /stylesheets
  static_dir: assets/stylesheets

- url: /js
  static_dir: assets/js

- url: /images
  static_dir: assets/images

- url: /views/(.*)/partials/(.*)
  static_files: views/\1/partials/\2
  upload: views/.*/partials/.*

- url: /_ah/spi/.*
  script: main_api.application

- url: /.*
  script: main.application

libraries:

# Google Cloud Endpoints.
- name: endpoints
  version: latest

# Templating.
- name: jinja2
  version: latest

# Route handling.
- name: webapp2
  version: latest

skip_files:
# Default settings.
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
# Custom.
- ^bin$
- ^bower_components$
- ^node_modules$
- ^(.*/)?.*\.less$
