application: care-tiger
version: 1-1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /stylesheets
  static_dir: assets/stylesheets

- url: /js
  static_dir: assets/js

- url: /images
  static_dir: assets/images

- url: /.*
  script: main.application

libraries:

- name: webapp2
  version: latest

- name: jinja2
  version: latest

skip_files:
# Default settings.
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
# Custom.
- ^bin$
